export const movies = [
  "Pirates of the Caribbean",
  "Interstellar",
  "Inception",
  "Jurassic Park",
  "Memento",
  "The Shawshank Redemption",
  "The Godfather",
  "Fight Club",
  "The Prestige",
  "Oppenheimer",
  "Lord of the rings",
  "Harry Potter",
  "The wolf of wall street",
  "Pulp Fiction",
  "Scarface",
  "Shutter Island",
  "Joker",
  "The Hobbit An Unexpected Journey",
  "Avengers endgame",
  "Requiem for a Dream",
];
