export const movies = [
  "Pirates of the Caribbean",
  "Interstellar",
  "Inception",
  "Jurassic Park",
  "Memento",
  "The Shawshank Redemption",
  "The Godfather",
  "Fight Club",
  "The Prestige",
  "Oppenheimer",
  "Lord of the rings",
  "Harry Potter",
  "The wolf of wall street",
  "Pulp Fiction",
  "Scarface",
  "Shutter Island",
  "Joker",
  "The Hobbit An Unexpected Journey",
  "Avengers endgame",
  "Requiem for a Dream",
  "Shrek",
  "The dark knight",
  "The matrix",
  "Titanic",
  "John Wick",
  "Get out",
  "Gladiator",
  "Forrest Gump",
  "Goodfellas",
  "The Hangover",
  "Guardians of the Galaxy",
  "Men in Black",
  "The hunger games",
  "Avatar",
  "The lion king",
];
