export const series = [
  "Breaking bad",
  "the walking dead",
  "game of thrones",
  "house of the dragon",
  "rick and morty",
  "westworld",
  "haunting of hill house",

  "Better Call Saul",
  "True detective",
  "Narcos",
  "The last of us",
  "Peaky blinders",
  "Dark",
  "The simpsons",
  "House",
  "Stranger things",
  "Mindhunter",
  "American Horror Story",
  "Mr robot",
  "Doctor who",
  "The bear",
  "Chernobyl",
  "The Office",
  "The big bang theory",
  "how i met your mother",
  "seinfeld",
  "black mirror",
  "the crown",
  "the blacklist",
  "orange is the new black",
  "you",
  "the wire",
  "money heist",
];
